# Automatically fetch and merge the master branch for new stable releases
name: Update stable branch

# Controls when the action will run. 
on:
  # Triggers the workflow on push events but only for new tags
  push:
    tags:
      - "*.*.*"

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "sync-new-release"
  sync-new-release:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@master
        with:
          fetch-depth: 0
      
      - name: Update mamolinux/stable for new release
        uses: devmasx/merge-branch@master
        with:
          type: now
          from_branch: master
          target_branch: mamolinux/stable
          github_token: ${{ github.token }}
